config/routes.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2015 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :people do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email, :avatar
      get :autocomplete_tags
      post :bulk_edit, :bulk_update, :send_mails
      delete :bulk_destroy
    end
    member do
      get 'tabs/:tab' => 'people#show', :as => "tabs"
      get 'load_tab' => 'people#load_tab', :as => "load_tab"
    end
end

resources :departments do
  member do
    get :autocomplete_for_person
    post :add_people
    delete :remove_person
  end
end

resources :people_settings do
  collection do
    get :autocomplete_for_user
  end
end

resources :people_queries

app/models/people_query.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2015 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

class PeopleQuery < Query
  self.queried_class = Principal

  VISIBILITY_PRIVATE = 0
  VISIBILITY_ROLES   = 1
  VISIBILITY_PUBLIC  = 2

  self.available_columns = [
    QueryColumn.new(:id, :sortable => "#{Person.table_name}.id", :default_order => 'desc', :caption => '#', :frozen => true, :inline => false),
    QueryColumn.new(:name, :sortable => lambda {Person.fields_for_order_statement}, :caption => :field_person_full_name),
    QueryColumn.new(:firstname, :sortable => "#{Person.table_name}.firstname", :caption => :field_firstname),
    QueryColumn.new(:lastname, :sortable => "#{Person.table_name}.lastname", :caption => :field_lastname),
    QueryColumn.new(:middlename, :sortable => "#{PeopleInformation.table_name}.middlename", :caption => :label_people_middlename),
    QueryColumn.new(:gender, :sortable => "#{PeopleInformation.table_name}.gender", :groupable => "#{PeopleInformation.table_name}.gender", :caption => :label_people_gender),
    QueryColumn.new(:email, :sortable => Redmine::VERSION.to_s >= '3.0' ? "email_addresses.address" : "#{Person.table_name}.mail", :caption => :field_mail),
    QueryColumn.new(:address, :sortable => "#{PeopleInformation.table_name}.address", :caption => :label_people_address),
    QueryColumn.new(:phone, :sortable => "#{PeopleInformation.table_name}.phone", :caption => :label_people_phone),
    QueryColumn.new(:skype, :sortable => "#{PeopleInformation.table_name}.skype", :caption => :label_people_skype ),
    QueryColumn.new(:twitter, :sortable => "#{PeopleInformation.table_name}.twitter", :caption => :label_people_twitter),
    QueryColumn.new(:facebook, :sortable => "#{PeopleInformation.table_name}.facebook", :caption => :label_people_facebook),
    QueryColumn.new(:linkedin, :sortable => "#{PeopleInformation.table_name}.linkedin", :caption => :label_people_linkedin),
    QueryColumn.new(:birthday, :sortable => "#{PeopleInformation.table_name}.birthday", :caption => :label_people_birthday),
    QueryColumn.new(:job_title, :sortable => "#{PeopleInformation.table_name}.job_title", :groupable => "#{PeopleInformation.table_name}.job_title", :caption => :label_people_job_title),
    QueryColumn.new(:background, :sortable => "#{PeopleInformation.table_name}.background", :caption => :label_people_background),
    QueryColumn.new(:appearance_date, :sortable => "#{PeopleInformation.table_name}.appearance_date", :caption => :label_people_appearance_date),
    QueryColumn.new(:last_login_on, :sortable => "#{Person.table_name}.last_login_on", :caption => :field_last_login_on),
    QueryColumn.new(:department_id, :sortable => "#{Department.table_name}.name", :groupable => "#{PeopleInformation.table_name}.department_id", :caption => :label_people_department),
    QueryColumn.new(:is_system, :sortable => "#{PeopleInformation.table_name}.is_system", :caption => :label_people_is_system),
    QueryColumn.new(:status, :sortable => "#{Person.table_name}.status", :caption => :field_status),
    QueryColumn.new(:tags, :caption => :label_people_tags_plural)
  ]

  scope :visible, lambda {|*args|
    user = args.shift || User.current

    if Redmine::VERSION.to_s < '2.4'
      field = 'is_public'
      public_value = true
      private_value = false
    else
      field = 'visibility'
      public_value = VISIBILITY_PUBLIC
      private_value = VISIBILITY_PRIVATE
    end

    if user.admin?
      where("#{table_name}.#{field} <> ? OR #{table_name}.user_id = ?", private_value, user.id)
    elsif user.logged?
      where("#{table_name}.#{field} = ? OR #{table_name}.user_id = ?", public_value, user.id)
    else
      where("#{table_name}.#{field} = ?", public_value)
    end
  }

  def visible?(user=User.current)
    return true if user.admin?
    case visibility
    when VISIBILITY_PUBLIC
      true
    else
      user.respond_to?(:id) && user.id == user_id
    end
  end

  def is_private?
    visibility == VISIBILITY_PRIVATE
  end

  def is_public?
    !is_private?
  end

  def visibility=(value)
    if Redmine::VERSION.to_s < '2.4'
      self.is_public = value.to_i == VISIBILITY_PUBLIC
    else
      self[:visibility] = value
    end
  end

  def visibility
    if Redmine::VERSION.to_s < '2.4'
      self.is_public ? VISIBILITY_PUBLIC : VISIBILITY_PRIVATE
    else
      self[:visibility]
    end
  end

  def editable_by?(user)
    return false unless user
    # Admin can edit them all and regular users can edit their private queries
    return true if user.admin? || (self.user_id == user.id)
    # Members can not edit public queries that are for all project (only admin is allowed to)
    is_public? && user.allowed_people_to?(:manage_public_people_queries)
  end

  def initialize(attributes=nil, *args)
    super attributes
    self.filters ||= { 'status' => {:operator => "=", :values => ['1']} }
  end

  def initialize_available_filters
    add_available_filter "firstname", :type => :string, :order => 0
    add_available_filter "lastname", :type => :string, :order => 1
    add_available_filter "middlename", :type => :string, :order => 2, :name => l(:label_people_middlename)
    add_available_filter("gender",
      :type => :list_optional, :values => [[l(:label_people_male), 0], [l(:label_people_female), 1]],
      :name => l(:label_people_gender),
      :order => 3
    )

    add_available_filter "address", :type => :string, :order => 4, :name => l(:label_people_address)
    add_available_filter "phone", :type => :string, :order => 5, :name => l(:label_people_phone)
    add_available_filter "skype", :type => :string, :order => 6, :name => l(:label_people_skype)
    add_available_filter "twitter", :type => :string, :order => 7, :name => l(:label_people_twitter)
    add_available_filter "facebook", :type => :string, :order => 8, :name => l(:label_people_facebook)
    add_available_filter "linkedin", :type => :string, :order => 9, :name => l(:label_people_linkedin)
    add_available_filter "birthday", :type => :date_past, :order => 10, :name => l(:label_people_birthday)
    add_available_filter "job_title", :type => :string, :order => 11, :name => l(:label_people_job_title)
    add_available_filter "background", :type => :string, :order => 13, :name => l(:label_people_background)
    add_available_filter "appearance_date", :type => :date_past, :order => 14, :name => l(:label_people_appearance_date)
    add_available_filter "last_login_on", :type => :date_past, :order => 15

    add_available_filter "is_system", :type => :list,
    :values => [
      [l(:general_text_yes), ActiveRecord::Base.connection.quoted_true.gsub(/'/, '')],
      [l(:general_text_no), ActiveRecord::Base.connection.quoted_false.gsub(/'/, '')]
     ], :order => 15, :name => l(:label_people_is_system)

    statuses = [ [l(:status_active), Principal::STATUS_ACTIVE.to_s],
                 [l(:status_registered), Principal::STATUS_REGISTERED.to_s],
                 [l(:status_locked) ,Principal::STATUS_LOCKED.to_s]]

    add_available_filter "status", :type => :list_optional,
     :order => 16,
     :name => l(:field_status),
     :values => statuses
    departments = []
    Department.department_tree(Department.order(:lft)) do |department, level|
      name_prefix = (level > 0 ? '-' * 2 * level + ' ' : '') #'&nbsp;'
      departments << [(name_prefix + department.name).html_safe, department.id.to_s]
    end
    add_available_filter("department_id", :type => :list_optional, :name => l(:label_people_department), :order => 17,
      :values => departments
    ) if departments.any?
    add_available_filter "tags", :type => :list, :values => Person.available_tags.collect{ |t| [t.name, t.name] }, :order => 18, :name => l(:label_people_tags_plural)
    add_custom_fields_filters(UserCustomField.where(:is_filter => true))
  end

  def default_columns_names
    @default_columns_names ||= [:id, :name, :email, :phone]
  end

  def available_columns
    return @available_columns if @available_columns
    @available_columns = self.class.available_columns.dup

    @available_columns += CustomField.where(:type => 'UserCustomField').all.collect {|cf| QueryCustomFieldColumn.new(cf) }
    @available_columns
  end

  def objects_scope(options={})
    scope = Person.where(:type => 'User').logged

    options[:search].split(' ').collect{ |search_string| scope = scope.seach_by_name(search_string) } if options[:search].present?

    includes =  (options[:include] || [] ) + [:department]
    includes << :email_address if Redmine::VERSION.to_s >= '3.0'

    scope = scope.eager_load(:information).includes( includes.uniq)

    unless self.filters['is_system']
      scope = scope.where("#{PeopleInformation.table_name}.is_system IS NULL OR #{PeopleInformation.table_name}.is_system = ?", ActiveRecord::Base.connection.quoted_false.gsub(/'/, ''))
    end

    scope = scope.where(statement).
      where(options[:conditions])

    scope
  end

  def object_count
    objects_scope.count
  rescue ::ActiveRecord::StatementInvalid => e
    raise StatementInvalid.new(e.message)
  end

  def object_count_by_group
    r = nil
    if grouped?
      begin
        # Rails3 will raise an (unexpected) RecordNotFound if there's only a nil group value

app/controllers/people_queries_controller.rb
class PeopleQueriesController < ApplicationController
  before_action :find_query, except: [:new, :create, :index]

  accept_api_auth :index

  helper :queries
  include QueriesHelper

  def index
    case params[:format]
    when 'xml', 'json'
      @offset, @limit = api_offset_and_limit
    else
      @limit = per_page_option
    end
    @query_count = PeopleQuery.visible.count
    @query_pages = Paginator.new @query_count, @limit, params['page']
    @queries = PeopleQuery.visible.
                    order("#{Query.table_name}.name").
                    limit(@limit).
                    offset(@offset).
                    all
    respond_to do |format|
      format.html
      format.api
    end
  end

  def new
    @query = PeopleQuery.new
    @query.user = User.current

    unless User.current.allowed_people_to?(:manage_public_people_queries) || User.current.admin?
      @query.visibility = PeopleQuery::VISIBILITY_PRIVATE
    end

    @query.build_from_params(params)
  end

  def create
    @query = PeopleQuery.new(params[:query])
    @query.user = User.current

    @query.build_from_params(params)

    unless User.current.allowed_people_to?(:manage_public_people_queries) || User.current.admin?
      @query.visibility = PeopleQuery::VISIBILITY_PRIVATE
    end

    @query.column_names = nil if params[:default_columns]

    if @query.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to url_for({:controller => "people", :action => "index", :query_id => @query.id})
    else
      render :action => 'new', :layout => !request.xhr?
    end
  end

  def edit
  end

  def update
    @query.attributes = params[:query]
    @query.build_from_params(params)

    unless User.current.allowed_people_to?(:manage_public_people_queries) || User.current.admin?
      @query.visibility = PeopleQuery::VISIBILITY_PRIVATE
    end

    @query.column_names = nil if params[:default_columns]

    if @query.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to url_for({:controller => "people", :action => "index", :query_id => @query.id})
    else
      render :action => 'edit'
    end
  end

  def destroy
    @query.destroy
    redirect_to url_for({:controller => "people_queries", :action => "index", :set_filter => 1})
  end

private

  def find_query
    @query = PeopleQuery.find(params[:id])
    render_403 unless @query.editable_by?(User.current)
  rescue ActiveRecord::RecordNotFound
    render_404
  end

end

app/views/people_queries/_form.html.erb
<%= error_messages_for 'query' %>

<div class="box">
  <div class="tabular">
    <%= hidden_field_tag 'gantt', '1' if params[:gantt] %>

    <p><label for="query_name"><%=l(:field_name)%></label>
    <%= text_field 'query', 'name', :size => 80 %></p>

    <% if User.current.admin? || User.current.allowed_people_to?(:manage_public_people_queries) %>
      <p><label><%=l(:field_visible)%></label>
        <label class="block"><%= radio_button 'query', 'visibility', PeopleQuery::VISIBILITY_PRIVATE %> <%= l(:label_visibility_private) %></label>
        <label class="block"><%= radio_button 'query', 'visibility', PeopleQuery::VISIBILITY_PUBLIC %> <%= l(:label_visibility_public) %></label>
      </p>
    <% end %>


    <fieldset><legend><%= l(:label_options) %></legend>
    <p><label for="query_default_columns"><%=l(:label_default_columns)%></label>
    <%= check_box_tag 'default_columns', 1, @query.has_default_columns?, :id => 'query_default_columns',
          :onclick => 'if (this.checked) {$("#columns").hide();} else {$("#columns").show();}' %></p>

    <p><label for="query_group_by"><%= l(:field_group_by) %></label>
    <%= select 'query', 'group_by', @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]}, :include_blank => true %></p>

    </fieldset>
  </div>

  <fieldset id="filters"><legend><%= l(:label_filter_plural) %></legend>
  <%= render :partial => 'queries/filters', :locals => {:query => query}%>
  </fieldset>


  <fieldset><legend><%= l(:label_sort) %></legend>
  <% 3.times do |i| %>
  <%= i+1 %>: 
  <%= label_tag "query_sort_criteria_attribute_" + i.to_s,
                l(:description_query_sort_criteria_attribute), :class => "hidden-for-sighted" %>
  <%= select_tag("query[sort_criteria][#{i}][]",
                 options_for_select([[]] + query.available_columns.select(&:sortable?).collect {|column| [column.caption, column.name.to_s]}, @query.sort_criteria_key(i)),
                 :id => "query_sort_criteria_attribute_" + i.to_s)%>
  <%= label_tag "query_sort_criteria_direction_" + i.to_s,
                l(:description_query_sort_criteria_direction), :class => "hidden-for-sighted" %>
  <%= select_tag("query[sort_criteria][#{i}][]",
                  options_for_select([[], [l(:label_ascending), 'asc'], [l(:label_descending), 'desc']], @query.sort_criteria_order(i)),
                  :id => "query_sort_criteria_direction_" + i.to_s) %>
  <br />
  <% end %>
  </fieldset>


  <%= content_tag 'fieldset', :id => 'columns', :style => (query.has_default_columns? ? 'display:none;' : nil) do %>
  <legend><%= l(:field_column_names) %></legend>
  <%= render_query_columns_selection(query) %>
  <% end %>

  </div>

<%= javascript_tag do %>
$(document).ready(function(){
  $("input[name='query[visibility]']").change(function(){
    var checked = $('#query_visibility_1').is(':checked');
    $("input[name='query[role_ids][]'][type=checkbox]").attr('disabled', !checked);
  }).trigger('change');
});
<% end %>

app/views/people_queries/edit.html.erb
<h2><%= l(:label_query) %></h2>

<%= form_tag(people_query_path(@query), :method => :put) do %>
  <%= render :partial => 'people_queries/form', :locals => {:query => @query} %>
  <%= submit_tag l(:button_save) %>
<% end %>

app/views/people_queries/index.html.erb
<div class="contextual">
<% if User.current.allowed_people_to?(:save_people_queries) %>
<%= link_to l(:label_query_new), { :controller => 'people_queries', :action => 'new' }, :class => 'icon icon-add'  %>
<% end %>
</div>

<h2><%= l(:label_query_plural) %></h2>
<% if @queries.empty? %>
  <p><i><%=l(:label_no_data)%></i></p>
<% else %>
  <table class="list">
  <% @queries.each do |query| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td class="name">
        <%= link_to h(query.name), :controller => "people", :action => 'index', :query_id => query %>
      </td>
      <td class="buttons">
        <% if query.editable_by?(User.current) %>
        <%= link_to l(:button_edit), edit_people_query_path(query), :class => 'icon icon-edit' %>
        <%= delete_link people_query_path(query) %>
      <% end %>
      </td>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/people_queries/new.html.erb
<h2><%= l(:label_query_new) %></h2>

<%= form_tag(people_queries_path) do %>
  <%= render :partial => 'people_queries/form', :locals => {:query => @query} %>
  <%= submit_tag l(:button_save) %>
<% end %>