config/routes.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2015 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :people do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email, :avatar
      get :autocomplete_tags
      post :bulk_edit, :bulk_update, :send_mails
      delete :bulk_destroy
    end
    member do
      get 'tabs/:tab' => 'people#show', :as => "tabs"
      get 'load_tab' => 'people#load_tab', :as => "load_tab"
    end
end

resources :departments do
  member do
    get :autocomplete_for_person
    post :add_people
    delete :remove_person
  end
end

resources :people_settings do
  collection do
    get :autocomplete_for_user
  end
end

resources :people_queries

app/models/person.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2015 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

class Person < User
  unloadable
  include Redmine::SafeAttributes

  self.inheritance_column = :_type_disabled

  has_one :information, :class_name => "PeopleInformation", :foreign_key => :user_id, :dependent => :destroy

  delegate :phone, :address, :skype, :birthday, :job_title, :company, :middlename, :gender, :twitter,
          :facebook, :linkedin, :department_id, :background, :appearance_date, :is_system,
          :to => :information, :allow_nil => true

  acts_as_customizable

  accepts_nested_attributes_for :information, :allow_destroy => true, :update_only => true, :reject_if => proc {|attributes| PeopleInformation.reject_information(attributes)}

  has_one :department, :through => :information

  rcrm_acts_as_taggable

  GENDERS = [[l(:label_people_male), 0], [l(:label_people_female), 1]]

  scope :in_department, lambda {|department|
    department_id = department.is_a?(Department) ? department.id : department.to_i
    eager_load(:information).where("(#{PeopleInformation.table_name}.department_id = ?) AND (#{Person.table_name}.type = 'User')", department_id)
  }
  scope :not_in_department, lambda {|department|
    department_id = department.is_a?(Department) ? department.id : department.to_i
    eager_load(:information).where("(#{PeopleInformation.table_name}.department_id != ?) OR (#{PeopleInformation.table_name}.department_id IS NULL)", department_id)
  }

  scope :seach_by_name, lambda {|search| eager_load(ActiveRecord::VERSION::MAJOR >= 4 ? [:information, :email_address] : [:information]).where("(LOWER(#{Person.table_name}.firstname) LIKE :search OR
                                                                    LOWER(#{Person.table_name}.lastname) LIKE :search OR
                                                                    LOWER(#{PeopleInformation.table_name}.middlename) LIKE :search OR
                                                                    LOWER(#{Person.table_name}.login) LIKE :search OR
                                                                    LOWER(#{(ActiveRecord::VERSION::MAJOR >= 4) ? (EmailAddress.table_name + '.address') : (Person.table_name + '.mail')}) LIKE :search)", {:search => search.downcase + "%"} )}

  validates_uniqueness_of :firstname, :scope => :lastname

  safe_attributes 'custom_field_values',
                  'custom_fields',
                  'information_attributes',
  :if => lambda {|person, user| (person.new_record? && user.allowed_people_to?(:add_people, person)) || user.allowed_people_to?(:edit_people, person) }

  safe_attributes 'status',
    :if => lambda {|person, user| user.allowed_people_to?(:edit_people, person) && person.id != user.id && !person.admin }

  safe_attributes 'tag_list',
    :if => lambda {|person, user| user.allowed_people_to?(:manage_tags, person) }

  def type
    'User'
  end

  def email
    self.mail
  end

  def project
    nil
  end

  def phones
    @phones || self.phone ? self.phone.split( /, */) : []
  end

  def next_birthday
    return if birthday.blank?
    year = Date.today.year
    mmdd = birthday.strftime('%m%d')
    year += 1 if mmdd < Date.today.strftime('%m%d')
    mmdd = '0301' if mmdd == '0229' && !Date.parse("#{year}0101").leap?
    return Date.parse("#{year}#{mmdd}")
  end

  def self.next_birthdays(limit = 10)
    Person.eager_load(:information).where("#{PeopleInformation.table_name}.birthday IS NOT NULL").sort_by(&:next_birthday).first(limit)
  end

  def age
    return nil if birthday.blank?
    now = Time.now
    age = now.year - birthday.year - (birthday.to_time.change(:year => now.year) > now ? 1 : 0)
  end

  def editable_by?(usr, prj=nil)
    true
    # usr && (usr.allowed_to?(:edit_people, prj) || (self.author == usr && usr.allowed_to?(:edit_own_invoices, prj)))
    # usr && usr.logged? && (usr.allowed_to?(:edit_notes, project) || (self.author == usr && usr.allowed_to?(:edit_own_notes, project)))
  end

  def visible?(user=User.current)
    if Redmine::VERSION.to_s >= "3.0"
      principal = Principal.visible(user).where(:id => id).first
      return principal.present?
    end
    true
  end

  def attachments_visible?(user=User.current)
    true
  end

  def available_custom_fields
    CustomField.where("type = 'UserCustomField'").sorted.to_a
  end

end

app/helpers/people_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2015 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

module PeopleHelper

  def birthday_date(person)
    ages = Setting.plugin_redmine_people["hide_age"].to_i > 0 ? '' : "(#{person.age + 1})"
    if person.birthday.day == Date.today.day && person.birthday.month == Date.today.month
       "#{l(:label_today).capitalize} #{ages}"
    else
      "#{person.birthday.day} #{t('date.month_names')[person.birthday.month]} #{ages}"
    end
  end

  def retrieve_people_query
    if params[:query_id].present?
      @query = PeopleQuery.find(params[:query_id])
      raise ::Unauthorized unless @query.visible?
      session[:people_query] = {:id => @query.id}
      sort_clear
    elsif api_request? || params[:set_filter] || session[:people_query].nil?
      # Give it a name, required to be valid
      @query = PeopleQuery.new(:name => "_")
      @query.build_from_params(params)
      session[:people_query] = {:filters => @query.filters, :group_by => @query.group_by, :column_names => @query.column_names}
    else
      # retrieve from session
      @query = PeopleQuery.find(session[:people_query][:id]) if session[:people_query][:id]
      @query ||= PeopleQuery.new(:name => "_", :filters => session[:people_query][:filters], :group_by => session[:people_query][:group_by], :column_names => session[:people_query][:column_names])
    end
  end

  def people_list_style
    list_styles = people_list_styles_for_select.map(&:last)
    if params[:people_list_style].blank?
      list_style = list_styles.include?(session[:people_list_style]) ? session[:people_list_style] : RedminePeople.default_list_style
    else
      list_style = list_styles.include?(params[:people_list_style]) ? params[:people_list_style] : RedminePeople.default_list_style
    end
    session[:people_list_style] = list_style
  end

  def people_list_styles_for_select
    list_styles = [[l(:label_people_list_excerpt), "list_excerpt"]]
    list_styles += [[l(:label_people_list_list), "list"]]
  end

  def people_principals_check_box_tags(name, principals)
    s = ''
    principals.each do |principal|
      s << "<label>#{ check_box_tag name, principal.id, false, :id => nil } #{principal.is_a?(Group) ? l(:label_group) + ': ' + principal.to_s : principal}</label>\n"
    end
    s.html_safe
  end

  def change_status_link(person)
    return unless User.current.allowed_people_to?(:edit_people, person) && person.id != User.current.id && !person.admin
    url = {:controller => 'people', :action => 'update', :id => person, :page => params[:page], :status => params[:status], :tab => nil}

    if person.locked?
      link_to l(:button_unlock), url.merge(:person => {:status => User::STATUS_ACTIVE}), :method => :put, :class => 'icon icon-unlock'
    elsif person.registered?
      link_to l(:button_activate), url.merge(:person => {:status => User::STATUS_ACTIVE}), :method => :put, :class => 'icon icon-unlock'
    elsif person != User.current
      link_to l(:button_lock), url.merge(:person => {:status => User::STATUS_LOCKED}), :method => :put, :class => 'icon icon-lock'
    end
  end

  def person_tag(person, options={})
    avatar_size = options.delete(:size) || 16
    if person.visible? && !options[:no_link]
      person_avatar = link_to(avatar(person, :size => avatar_size), person_path(person), :id => "avatar")
      person_name = link_to(person.name, person_path(person))
    else
      person_avatar = avatar(person, :size => avatar_size)
      person_name = person.name
    end

    case options.delete(:type).to_s
    when "avatar"
      person_avatar.html_safe
    when "plain"
      person_name.html_safe
    else
      content_tag(:span, "#{person_avatar} #{person_name}".html_safe, :class => "person")
    end
  end
  def person_to_vcard(person)
    card = Vcard::Vcard::Maker.make2 do |maker|

      maker.add_name do |name|
        name.prefix = ''
        name.given = person.firstname.to_s
        name.family = person.lastname.to_s
        name.additional = person.middlename.to_s
      end

      maker.add_addr do |addr|
        addr.preferred = true
        addr.street = person.address.to_s.gsub("\r\n"," ").gsub("\n"," ")
      end

      maker.title = person.job_title.to_s
      maker.org = person.company.to_s
      maker.birthday = person.birthday.to_date unless person.birthday.blank?
      maker.add_note(person.background.to_s.gsub("\r\n"," ").gsub("\n", ' '))

      # maker.add_url(person.website.to_s)

      person.phones.each { |phone| maker.add_tel(phone) }

      maker.add_email(person.email)
    end
    avatar = person.avatar
    card = card.encode.sub("END:VCARD", "PHOTO;BASE64:" + "\n " + [File.open(avatar.diskfile).read].pack('m').to_s.gsub(/[ \n]/, '').scan(/.{1,76}/).join("\n ") + "\nEND:VCARD") if avatar && avatar.readable?

    card.to_s

  end

  def sidebar_people_queries(query_class)
    unless @sidebar_queries
      @sidebar_queries = query_class.visible.
        order("#{query_class.table_name}.name ASC")
    end
    @sidebar_queries
  end

  def people_query_links(title, queries, object_type)
    # links to #index on contacts/show
    return '' unless queries.any?
    url_params = controller_name == "#{object_type}s" ? {:controller => "#{object_type}s", :action => 'index'} : params
    content_tag('h3', title) + "\n" +
      content_tag('ul',
        queries.collect {|query|
            css = 'query'
            css << ' selected' if query == @query
            content_tag('li', link_to(query.name, url_params.merge(:query_id => query), :class => css))
          }.join("\n").html_safe,
        :class => 'queries'
      ) + "\n"
  end

  def render_sidebar_people_queries(object_type)
    query_class = Object.const_get("#{object_type.camelcase}Query")
    out = ''.html_safe
    out << people_query_links(l(:label_my_queries),  sidebar_people_queries(query_class).select(&:is_private?), object_type)
    out << people_query_links(l(:label_query_plural),  sidebar_people_queries(query_class).reject(&:is_private?), object_type)
    out
  end

  def people_tabs
    [{:name => 'activity', :partial => 'activity', :label => l(:label_activity)},
     {:name => 'files', :partial => 'attachments', :label => l(:label_attachment_plural)},
     {:name => 'projects', :partial => 'projects', :label => l(:label_project_plural)}
    ]
  end

  def render_people_tabs(tabs)
    if tabs.any?
      render :partial => 'common/people_tabs', :locals => {:tabs => tabs}
    else
      content_tag 'p', l(:label_no_data), :class => "nodata"
    end
  end

end

app/views/people/_attachments.html.erb
<div id="person_files">
  <div class="contextual">     
    <%= link_to l(:button_add), {}, :onclick => "$('#add_attachment_form').show(); $('#add_attachment_link').hide(); return false;", :class => 'icon icon-add', :id => 'add_attachment_link' if User.current.allowed_people_to?(:edit_people, @person) %> 
  </div>
  <%= labelled_form_for :person, @person, 
                               :url => {:action => 'update', :id => @person}, 
                               :html => { :multipart => true, :method => :put, :id => "add_attachment_form", :style => "display:none;" } do |f|  %>
      <fieldset>
        <%= error_messages_for 'person' %>

        <p><%=l(:label_attachment_plural)%><br /><%= render :partial => 'attachments/form', :locals => {:container => @person} %></p>
        <%= submit_tag l(:button_save) -%>   
        <%= link_to l(:button_cancel), {}, :onclick => "$('#add_attachment_form').hide(); $('#add_attachment_link').show(); return false;"  %>  
      </fieldset>
  <% end -%>
  <%= render :partial => 'attachments/links', :locals => {:attachments => @person_attachments, :options  => {:author => true, :deletable => :true}, :thumbnails => Setting.thumbnails_enabled?} %>
</div>

app/views/people/_list.html.erb
<%= form_tag({}) do %>
<%= hidden_field_tag 'back_url', url_for(params) %>
<div class="autoscroll">
  <table class="list people">
    <thead>
      <tr>
        <th class="checkbox hide-when-print"><%= link_to image_tag('toggle_check.png'), {}, :onclick => 'toggleIssuesSelection(this); return false;',
                                                           :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
        </th>
        <% @query.columns.each do |column| %>
          <%= column_header(column) %>
        <% end %>
      </tr>
    </thead>

  <% previous_group = false %>
  <tbody>
  <% @people.each do |person| -%>
    <% if @query.grouped? && (group = @query.group_by_column.value(person)) != previous_group %>
      <% reset_cycle %>
      <tr class="group open">
        <td colspan="<%= @query.columns.size + 2 %>">
          <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
          <%= group.blank? ? l(:label_none) : column_content(@query.group_by_column, person) %> <span class="count">(<%= @people_count_by_group[group] %>)</span>
          <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}", "toggleAllRowGroups(this)", :class => 'toggle-all') %>
        </td>
      </tr>
      <% previous_group = group %>
    <% end %>


    <tr id="person-<%= h(person.id) %>" class="hascontextmenu">
      <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", person.id, false, :id => nil) %></td>
      <% @query.columns.each do |column| %><%= content_tag 'td', column_content(column, person), :class => column.css_classes %><% end %>
    </tr>
    <% end %>
    </tbody>
  </table>

 </div>
<% end %>

app/views/people/_person_birthday.html.erb
<table class="person_data" id="person_birthday_<%= person_birthday.id %>">
  <tr>
    <td class="avatar"><%= link_to avatar(person_birthday, :size => "32"), person_path(person_birthday), :id => "avatar" %></td>
    <td class="name">
      <h4 class="contacts_header">
        <%= link_to person_birthday.name, person_path(person_birthday) %>
      </h4>
      <p>
          <span class="birthday bday" title="<%="#{format_date(person_birthday.birthday)}"%>"><%= birthday_date(person_birthday) %></span>

      </p>
    </td> 
  </tr>
</table>  

app/views/people/_person_data.html.erb
<table class="person_data" id="person_data_<%= person_data.id %>">
  <tr>
    <td class="avatar"><%= link_to avatar(person_data, :size => "32"), person_path(person_data), :id => "avatar" %></td>
    <td class="name">
      <h4 class="contacts_header">
        <%= link_to person_data.name, person_path(person_data) %>
      </h4>
      <p>
          <span class="job_title"><%= person_data.job_title %></span>

      </p>
    </td> 
  </tr>
</table>  

app/views/people/_person_tag_list.html.erb
<%= raw @tags.collect {|tag|
       tag.name
    }.to_json
%>

app/views/people/_projects.html.erb
<% unless @memberships.empty? %>
<ul>
<% for membership in @memberships %>
  <li><%= link_to_project(membership.project) %>
    (<%=h membership.roles.sort.collect(&:to_s).join(', ') %>, <%= format_date(membership.created_on) %>)</li>
<% end %>
</ul>
<% end %>

app/views/people/edit.html.erb
<div class="contextual">  
    <%= link_to(l(:button_people_edit_profile), edit_user_path(@person), :class => 'icon icon-edit') if User.current.admin? %>
</div>    

<h2><%= l(:label_people_edit_person) %></h2>

<%= labelled_form_for :person, @person, 
                             :url => {:action => 'update', :id => @person}, 
                             :html => { :multipart => true, :method => :put, :id => "person_form" } do |f|  %>
  <%= error_messages_for 'person' %>

  <%= render :partial => 'form', :locals => {:f => f} %>    
  <%= submit_tag l(:button_save) -%>    
<% end -%>

<% content_for :sidebar do %>
<% end %>

<% content_for :header_tags do %>
  <%= javascript_include_tag :redmine_people, :plugin => 'redmine_people'  %>
  <%= stylesheet_link_tag :redmine_people, :plugin => 'redmine_people' %>
  <%= robot_exclusion_tag %>
<% end %>

app/views/people/index.html.erb
<div class="contextual">
    <% if !@query.new_record? && @query.editable_by?(User.current) %>
    <%= link_to l(:button_people_edit_query), edit_people_query_path(@query), :class => 'icon icon-edit' %>
    <%= link_to l(:button_people_delete_query), people_query_path(@query), :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' %>
    <% end %>
    <%= link_to l(:label_user_new), {:controller => 'people', :action => 'new', :department_id => @department}, :class => 'icon icon-add' if User.current.allowed_people_to?(:add_people, @person) %>
    <%= call_hook(:view_people_action_menu) %>
</div>

<% html_title(@query.new_record? ? l(:label_people) : @query.name) %>

<div class="filters">
	<%= form_tag({:contoller => "people", :action => "index"}, :method => :get,  :id => "query_form") do %>
    <%= hidden_field_tag 'set_filter', '1' %>

    <script type="text/javascript">
       jQuery(function($) {
          // when the #search field changes
          $("#search").observe_field(2, function() {
            var form = $("#query_form"); // grab the form wrapping the search bar.
            var url = form.attr("action");
            form.find('[name="c[]"] option').each(function(i, elem){
              $(elem).attr('selected', true)
            });
            var formData = form.serialize();
            form.find('[name="c[]"] option').each(function(i, elem){
              $(elem).attr('selected', false)
            });
            $.get(url, formData, function(data) { // perform an AJAX get, the trailing function is what happens on successful get.
                $("#people_list").html(data); // replace the "results" div with the result of action taken
            });
          });
        });
    </script>

    <h2 class="people_header">
        <span id='scope_header' class="scope_title">
        <%= @query.new_record? ? l(:label_people) : @query.name %>
        </span>

        <span class="live_search">
            <%= text_field_tag(:search, params[:search], :autocomplete => "off", :class => "live_search_field", :placeholder => l(:label_people_search) ) %>
        </span>
        <span class="tags">
            <%= people_tag_links(@filter_tags) %>
        </span>
    </h2>
    <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
      <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
      <div style="<%= @query.new_record? ? "" : "display: none;" %>">
        <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
      </div>
    </fieldset>

    <fieldset class="collapsible collapsed">
      <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
      <div style="display: none;">
        <table>
          <% if people_list_style != 'list_excerpt' %>
          <tr>
            <td><%= l(:field_column_names) %></td>
            <td><%= render_query_columns_selection(@query) %></td>
          </tr>
          <% end %>
          <tr>
          <td><label for='group_by'><%= l(:field_group_by) %></label></td>
          <td><%= select_tag('group_by', options_for_select([[]] + @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]}, @query.group_by)) %></td>
          <% if people_list_style != 'list' %>
            <td><label for='sort'><%= l(:label_sort) %></label></td>
            <td><%= select_tag('sort',
                               options_for_select(
                                 [[]] +
                                 [[l(:label_people_job_title), "job_title"],
                                  [l(:label_people_department), "department_id"],
                                  [l(:field_created_on), "created_on:desc"],
                                  [l(:field_updated_on), "updated_on:desc"]],
                                 params[:sort])
                       ) %></td>
          <% end %>
          </tr>
          <tr>
            <td><label for='people_list_style'><%= l(:label_people_list_partial_style) %></label></td>
            <td><%= select_tag('people_list_style', options_for_select(people_list_styles_for_select, people_list_style)) %></td>
          </tr>
        </table>
      </div>
    </fieldset>
    <p class="buttons hide-when-print">
      <%= link_to l(:button_apply), "#", :onclick=>"$('#query_form').submit()", :class => 'icon icon-checked' %>
      <%= link_to l(:button_clear), { :set_filter => 1 }, :class => 'icon icon-reload'  %>
      <% if @query.new_record? && User.current.logged? %>
        <%= link_to_function l(:button_save),
                             "$('#query_form').attr('action', '#{ new_people_query_path }').submit()",
                             :class => 'icon icon-save' %>
      <% end %>
    </p>
	<% end %>
</div>
<%= error_messages_for 'query' %>

<div id="people_list">
<% if @people.blank? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
    <%= render :partial => people_list_style %>
    <p class="pagination"><%= pagination_links_full @people_pages, @people_count %></p>
<% end %>
</div>
<% other_formats_links do |f| %>
    <%= f.link_to 'CSV', :url => params %>
<% end if false%>

<% html_title l(:label_people) %>

<%= context_menu url_for( {:controller => "people", :action => "context_menu"} )%>

<% content_for :sidebar do %>
  <div id="queries">
    <%= render_sidebar_people_queries('people') %>
  </div>

  <% unless @departments.blank? %>
  <div id="people_departments">
    <div class="contextual">
      <%= link_to l(:button_edit), departments_path if User.current.allowed_people_to?(:edit_departments) %>
    </div>
    <h3><%= l(:label_department_plural) %></h3>
    <%= department_tree_links(@departments) %>
  </div>
  <% end %>
  <div id="tags">
    <%= render :partial => 'tags_cloud', :object => @tags %>
  </div>

  <div id="next_birthdays">
    <h3><%= l(:label_people_next_birthdays) %></h3>
    <%= render :partial => 'person_birthday', :collection => @next_birthdays %>
  </div>

  <div id="new_people">
    <h3><%= l(:label_people_new_people) %></h3>
    <%= render :partial => 'person_data', :collection => @new_people %>
  </div>

<% end %>

<% content_for :header_tags do %>
    <%= javascript_include_tag :redmine_people, :plugin => 'redmine_people'  %>
	<%= stylesheet_link_tag :redmine_people, :plugin => 'redmine_people' %>
	<meta name = "format-detection" content = "telephone=no">
<% end %>

app/views/people/show.html.erb
<%= error_messages_for 'person' %>

<% html_title "#{l(:label_people_person)} ##{@person.id}: #{@person.name}" %>

<div class="contextual">
  <%= link_to l(:label_profile), user_path(@person), :class => 'icon icon-user' %>
  <%= link_to l(:button_edit), {:controller => 'people', :action => 'edit', :id => @person}, :class => 'icon icon-edit' if User.current.allowed_people_to?(:edit_people, @person) %>
  <%= change_status_link(@person) %>
</div>

<h2><%= l(:label_people_person) %> #<%= @person.id %></h2>
<div class="person details">
  <%= content_tag('span', l(:label_people_is_system), :class => 'system')  if  @person.is_system %>
  <table class="subject_header">
    <tr>
      <td class="avatar"><%= link_to avatar(@person, :size => "64", :full_size => true), @person.avatar %></td>
      <td class="name" style="vertical-align: top;">
        <h1><%= h @person.name %></h1>
        <p>
          <%= h @person.job_title %>
          <% if @person.department %>
            <%= " #{l(:label_people_at_department)} " %>
            <%= department_tree_tag @person %>
          <% end %>
        </p>
        <%= render :partial => 'form_tags', :object => @person.tags, :locals => {:editable => true} %>
      </td>
      <td class="subject_info">
        <ul>
          <% if @person.phones.any? %>
            <li class="phone icon icon-phone"><%=  @person.phones.first %></li>
          <% end %>
          <li class="email icon icon-email"><%= mail_to @person.email %></li>
        </ul>
      </td>
    </tr>
  </table>

  <%= call_hook(:view_people_show_details_bottom, :person => @person) %>
</div>

<%= render_people_tabs people_tabs%>


<% content_for :sidebar do %>
  <%= render :partial => 'attributes' %>
  <%= call_hook(:view_people_sidebar_after_attributes, :person => @person) %>
  <% if !@person.background.blank? %>
    <h3><%= l(:label_people_background) %></h3>
    <div class="wiki"><%= textilizable(@person, :background) %></div>
  <% end %>
<% end %>



<% content_for :header_tags do %>
  <%= javascript_include_tag :redmine_people, :plugin => 'redmine_people'  %>
  <%= stylesheet_link_tag :redmine_people, :plugin => 'redmine_people' %>
<% end %>