config/routes.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2015 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :people do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email, :avatar
      get :autocomplete_tags
      post :bulk_edit, :bulk_update, :send_mails
      delete :bulk_destroy
    end
    member do
      get 'tabs/:tab' => 'people#show', :as => "tabs"
      get 'load_tab' => 'people#load_tab', :as => "load_tab"
    end
end

resources :departments do
  member do
    get :autocomplete_for_person
    post :add_people
    delete :remove_person
  end
end

resources :people_settings do
  collection do
    get :autocomplete_for_user
  end
end

resources :people_queries

app/models/department.rb
class Department < ActiveRecord::Base
  include Redmine::SafeAttributes

  belongs_to :head, class_name: 'Person', foreign_key: 'head_id'

  has_many :people_information, class_name: 'PeopleInformation', dependent: :nullify

  if ActiveRecord::VERSION::MAJOR >= 4
    has_many :people, -> { distinct }, class_name: 'Person', through: :people_information
  else
    has_many :people, class_name: 'Person', through: :people_information, uniq: true
  end

  if Redmine::VERSION.to_s < '3.0'
    acts_as_nested_set order: 'name', dependent: :destroy
  else
    include DepartmentNestedSet
  end

  # acts_as_attachable_global
  acts_as_attachable

  validates :name, presence: true, uniqueness: true

  safe_attributes 'name', 'background', 'parent_id', 'head_id'

  def to_s
    name
  end

  def self.department_tree(departments, &block)
    ancestors = []
    departments.sort_by(&:lft).each do |department|
      while ancestors.any? && !department.is_descendant_of?(ancestors.last)
        ancestors.pop
      end
      yield department, ancestors.size
      ancestors << department
    end
  end

  def css_classes
    s = 'project'
    s << ' root' if root?
    s << ' child' if child?
    s << (leaf? ? ' leaf' : ' parent')
    s
  end

  def allowed_parents
    return @allowed_parents if @allowed_parents

    @allowed_parents = Department.all - self_and_descendants - [self]
    @allowed_parents << nil
  end
end

app/controllers/departments_controller.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2015 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

class DepartmentsController < ApplicationController
  unloadable

  before_action :find_department, except: [:index, :create, :new]
  before_action :require_admin, only: [:destroy, :new, :create]
  before_action :authorize_people, only: [:update, :edit, :add_people, :remove_person]


  helper :attachments

  def index
    @departments = Department.all
  end

  def edit
  end

  def new
    @department = Department.new
  end

  def show
  end

  def update
    @department.safe_attributes = params[:department]

    if @department.save 
      respond_to do |format| 
        format.html { redirect_to :action => "show", :id => @department } 
        format.api  { head :ok }
      end
    else
      respond_to do |format|
        format.html { render :action => 'edit' }
        format.api  { render_validation_errors(@department) }
      end      
    end    
  end  

  def destroy  
    if @department.destroy
      flash[:notice] = l(:notice_successful_delete)
      respond_to do |format|
        format.html { redirect_to :controller => "people_settings", :action => "index", :tab => "departments" } 
        format.api { render_api_ok }
      end      
    else
      flash[:error] = l(:notice_unsuccessful_save)
    end

  end  

  def create
    @department = Department.new
    @department.safe_attributes = params[:department]

    if @department.save 
      respond_to do |format| 
        format.html { redirect_to :action => "show", :id => @department } 
        # format.html { redirect_to :controller => "people_settings", :action => "index", :tab => "departments" } 
        format.api  { head :ok }
      end
    else
      respond_to do |format|
        format.html { render :action => 'new' }
        format.api  { render_validation_errors(@department) }
      end      
    end
  end  

  def add_people
    @people = PeopleInformation.where(:user_id => params[:person_id] || params[:person_ids])
    @department.people_information << @people if request.post?
    respond_to do |format|
      format.html { redirect_to :controller => 'departments', :action => 'edit', :id => @department, :tab => 'people' }
      format.js
      format.api { render_api_ok }
    end
  end

  def remove_person
    @department.people_information.delete(PeopleInformation.find(params[:person_id])) if request.delete?
    respond_to do |format|
      format.html { redirect_to :controller => 'departments', :action => 'edit', :id => @department, :tab => 'people' }
      format.js
      format.api { render_api_ok }
    end
  end


  def autocomplete_for_person
    @people = Person.active.where(:type => 'User').not_in_department(@department).like(params[:q]).limit(100)
    render :layout => false
  end  

private
  def find_department
    @department = Department.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def authorize_people
    allowed = case params[:action].to_s
      when "create", "new"
        User.current.allowed_people_to?(:add_departments, @person)
      when "update", "edit", "add_people", "remove_person"
        User.current.allowed_people_to?(:edit_departments, @person)
      when "delete"
        User.current.allowed_people_to?(:delete_departments, @person)
      when "index", "show"
        User.current.allowed_people_to?(:view_departments, @person)
      else
        false
      end    

    if allowed
      true
    else  
      deny_access  
    end
  end  

end

app/helpers/departments_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2015 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

module DepartmentsHelper
  def department_tree(departments, &block)
    Department.department_tree(departments, &block)
  end

  def parent_department_select_tag(department)
    selected = department.parent if department
    # retrieve the requested parent department
    parent_id = (params[:department] && params[:department][:parent_id]) || params[:parent_id]
    if parent_id
      selected = (parent_id.blank? ? nil : Department.find(parent_id))
    end
    departments = department ? department.allowed_parents.compact : Department.all
    options = ''
    options << "<option value=''></option>"
    options << department_tree_options_for_select(departments, :selected => selected)
    content_tag('select', options.html_safe, :name => 'department[parent_id]', :id => 'department_parent_id')
  end

  def department_tree_options_for_select(departments, options = {})
    s = ''
    department_tree(departments) do |department, level|
      name_prefix = (level > 0 ? '&nbsp;' * 2 * level + '&#187; ' : '').html_safe
      tag_options = {:value => department.id}
      if department == options[:selected] || department.id == options[:selected] || (options[:selected].respond_to?(:include?) && options[:selected].include?(department))
        tag_options[:selected] = 'selected'
      else
        tag_options[:selected] = nil
      end
      tag = options[:tag] || 'option'
      tag_options.merge!(yield(department)) if block_given?
      s << content_tag(tag, name_prefix + h(department), tag_options)
    end
    s.html_safe
  end

  def department_tree_links(departments, options = {})
    s = ''
    s << "<ul class='department-tree'>"
    s << "<li> #{link_to(l(:label_people_all), :set_filter => 1)} </li>"
    department_tree(departments) do |department, level|
      name_prefix = (level > 0 ? ('&nbsp;' * 2 * level + '&#187; ') : '')
      s << "<li>" + name_prefix + people_department_link(department , :class => "#{'selected' if @department && department == @department}")
      s << "</li>"
    end
    s << "</ul>"
    s.html_safe
  end

  def people_department_link(department, options={})
    p = {:controller => 'people',
     :action => 'index',
     :set_filter => 1,
     :fields => [:department_id],
     :values => {:department_id => [department.id]},
     :operators => {:department_id => '='}
    }.merge(options)
    link_to department.name, p, options
  end

end

app/views/departments/_form.html.erb
<%= error_messages_for @department %>

<div class="box tabular">
<p><%= f.text_field :name, :required => true %></p>
<p><%= f.text_area :background, :rows => 5, :label => :label_people_background, :class => 'wiki-edit' %></p>
<p><%= f.select :head_id, options_for_select(Person.active.in_department(@department).order(:lastname).order(:firstname).map{|d| [d.name, d.id]}.insert(0, ['', '']), :selected => @department.head_id), :label => l(:label_department_head) %></p>
<% unless @department.allowed_parents.compact.empty? %>
    <p><%= label(:department, :parent_id, l(:field_department_parent)) %><%= parent_department_select_tag(@department) %></p>
<% end %>
</div>

app/views/departments/_general.html.erb
  <%= labelled_form_for @department do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>

  <%= submit_tag l(:button_save) %>
  <% end %>

app/views/departments/_people.html.erb
<div class="splitcontentleft">
<% if @department.people.any? %>
  <table class="list people">
    <thead><tr>
      <th><%= l(:label_user) %></th>
      <% if User.current.allowed_people_to?(:edit_people) %>
      <th style="width:15%"></th>
      <% end %>
    </tr></thead>
    <tbody>
    <% @department.people.sort.each do |person| %>
      <tr id="person-<%= person.id %>" class="<%= cycle 'odd', 'even' %>">
        <td class="person"><%= link_to_user person %></td>
        <% if User.current.allowed_people_to?(:edit_people) %>
        <td class="buttons">
          <%= delete_link url_for(:action => "remove_person", :id => @department, :person_id => person), :remote => true %>
        </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
</div>

<div class="splitcontentright">
<% people = Person.active.where(:type => 'User').not_in_department(@department).limit(100) %>
<% if people.any? %>
  <%= form_for(@department, :remote => true, :url => {:action => "add_people", :id => @department},
               :html => {:method => :post, :class => "select-users"}) do |f| %>
    <fieldset><legend><%=l(:label_user_new)%></legend>

    <p><%= label_tag "user_search", l(:label_user_search) %><%= text_field_tag 'user_search', nil %></p>
    <%= javascript_tag "observeSearchfield('user_search', 'people', '#{ escape_javascript url_for(:action => "autocomplete_for_person", :id => @department)}')" %>

    <div id="people">
      <%= principals_check_box_tags 'person_ids[]', people %>
    </div>

    <p><%= submit_tag l(:button_add) %></p>
    </fieldset>
  <% end %>
<% end %>

</div>

app/views/departments/add_people.js.erb
$('#tab-content-people').html('<%= escape_javascript(render :partial => 'departments/people') %>');
<% @people.each do |person| %>
  $('#person-<%= person.id %>').effect("highlight");
<% end %>

app/views/departments/autocomplete_for_person.html.erb
<%= principals_check_box_tags 'person_ids[]', @people %>

app/views/departments/edit.html.erb
<h2><%= l(:label_department) %></h2>


<% person_tabs = [{:name => 'general', :partial => 'general', :label => :label_general},
        {:name => 'people', :partial => 'people', :label => :label_people}
        ]   %>   

<%= render_tabs person_tabs %>  

<% content_for :header_tags do %>
  <%= javascript_include_tag :redmine_people, :plugin => 'redmine_people'  %>
  <%= stylesheet_link_tag :redmine_people, :plugin => 'redmine_people' %>
<% end %>

app/views/departments/index.html.erb
<%= render  :partial => "people_settings/departments" %>

<% html_title(l(:label_department_plural)) -%>

<% content_for :header_tags do %>
  <%= javascript_include_tag :redmine_people, :plugin => 'redmine_people'  %>
  <%= stylesheet_link_tag :redmine_people, :plugin => 'redmine_people' %>
<% end %>

app/views/departments/new.html.erb
<h2><%= l(:label_department_new) %></h2>

<%= labelled_form_for @department, :url => departments_path(@department)  do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_create) %>
<% end %>

<% content_for :header_tags do %>
  <%= javascript_include_tag :redmine_people, :plugin => 'redmine_people'  %>
  <%= stylesheet_link_tag :redmine_people, :plugin => 'redmine_people' %>
<% end %>

app/views/departments/remove_person.js.erb
$('#tab-content-people').html('<%= escape_javascript(render :partial => 'departments/people') %>');

app/views/departments/show.html.erb
<%= error_messages_for 'department' %>

<% html_title "#{l(:label_department)} ##{@department.id}: #{@department.name}" %>

<div class="contextual">
  <%= link_to l(:button_edit), edit_department_path(@department), :class => 'icon icon-edit' if User.current.allowed_people_to?(:edit_departments) %>
  <%= link_to l(:button_delete), department_path(@department), :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' if User.current.allowed_people_to?(:delete_departments) %>
</div>

<h2><%= l(:label_department) %> #<%= @department.id %></h2>

<div class="department issue details">


  <%= avatar(@department.head, :size => "50") %>

<div class="subject">
<h3><%= @department.name %></h3>
</div>
        <p class="author">
          <%= l(:label_department_head) %>
          <%= link_to_user @department.head %>
        </p>

  <% if @department.background? || @department.attachments.any? -%>

  <% if @department.background? %>
    <p><strong><%=l(:label_people_background)%></strong></p>
    <div class="wiki">
    <%= textilizable @department, :background, :attachments => @department.attachments %>
    </div>
  <% end %>
  <%= link_to_attachments @department, :thumbnails => true %>
  <% end -%>
</div>

<% content_for :sidebar do %>
  <div id="department_people">
    <h3><%= l(:label_people) %></h3>
    <%= render :partial => 'people/person_data', :collection => @department.people.active %>
  </div>

<% end %>

<% content_for :header_tags do %>
  <%= javascript_include_tag :redmine_people, :plugin => 'redmine_people'  %>
  <%= stylesheet_link_tag :redmine_people, :plugin => 'redmine_people' %>
<% end %>