config/routes.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2011-2015 Kirill Bezrukov
# http://www.redminecrm.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :people do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email, :avatar
      get :autocomplete_tags
      post :bulk_edit, :bulk_update, :send_mails
      delete :bulk_destroy
    end
    member do
      get 'tabs/:tab' => 'people#show', :as => "tabs"
      get 'load_tab' => 'people#load_tab', :as => "load_tab"
    end
end

resources :departments do
  member do
    get :autocomplete_for_person
    post :add_people
    delete :remove_person
  end
end

resources :people_settings do
  collection do
    get :autocomplete_for_user
  end
end

resources :people_queries

app/views/common/_people_tabs.html.erb
<% selected_tab = params[:tab] ? params[:tab].to_s : tabs.first[:name] %>

<div class="tabs">
  <ul>
    <% tabs.each do |tab| -%>
        <li><%= link_to tab[:label], tabs_person_path(@person, :tab => tab[:name]),
                        :id => "tab-#{tab[:name]}",
                        :class => (tab[:name] != selected_tab ? 'tab-header' : 'selected tab-header'),
                        :data => { :name => tab[:name], :partial => tab[:partial]},
                        :onclick => "showPeopleTab('#{tab[:name]}'); this.blur(); return false;" %></li>
    <% end -%>
  </ul>
  <div class="tabs-buttons" style="display:none;">
    <button class="tab-left" onclick="moveTabLeft(this);"></button>
    <button class="tab-right" onclick="moveTabRight(this);"></button>
  </div>
</div>

<% tabs.each do |tab| %>
    <% selected = tab[:name] == selected_tab %>
    <div class="tab-placeholder tab-content <%= 'active loaded' if selected %>" id="tab-placeholder-<%= tab[:name] %>" style="<%= "display: block" if selected %>">
      <%= render(:partial => tab[:partial]) if selected %>
    </div>
<% end %>
<script type='text/javascript'>
  $(document).ready(displayTabsButtons);
  $(window).resize(displayTabsButtons);
  $(document).ready(function(){ setupDeferredTabs('<%= load_tab_person_path(@person) %>') });
</script>